version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns: ["*"]
    labels:
      - "dependencies"
    reviewers:
      - "Automattic/vip-plugins"
    commit-message:
      prefix: "Actions"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      dev-dependencies:
        patterns:
          - "automattic/*"
          - "dealerdirect/*"
          - "php-parallel-lint/*"
          - "phpcompatibility/*"
          - "phpunit/*"
          - "squizlabs/*"
          - "yoast/*"
    labels:
      - "dependencies"
    reviewers:
      - "Automattic/vip-plugins"
    commit-message:
      prefix: "Composer"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      dev-dependencies:
        patterns:
          - "@wordpress/*"
    labels:
      - "dependencies"
    reviewers:
      - "Automattic/vip-plugins"
    commit-message:
      prefix: "npm"
      include: "scope"
    open-pull-requests-limit: 5
